<div class="container" style="font-size: small;">

    <h3 class="font-weight-bold">Data KUA</h3>
    <hr>
    <h5>DATA PEMELUK AGAMA</h5>
    <div class="table-responsive">
        <table width="100%" class="table table-success text-center table-hover">
            <tbody>
                <tr>
                    <th rowspan="2">
                        <p>NO</p>
                    </th>
                    <th rowspan="2">
                        <p>KEL. /DESA</p>
                    </th>
                    <th rowspan="2">
                        <p>JUMLAH</p>
                    </th>
                    <th colspan="5">
                        <p>JUMLAH PEND. MENURUT AGAMA</p>
                    </th>
                </tr>
                <tr>
                    <th>
                        <p>Islam</p>
                    </th>
                    <th>
                        <p>Katolik</p>
                    </th>
                    <th>
                        <p>Protestan</p>
                    </th>
                    <th>
                        <p>Hindu</p>
                    </th>
                    <th>
                        <p>Budha</p>
                    </th>
                </tr>
                <tr>
                    <td>
                        <p>1</p>
                    </td>
                    <td>
                        <p>Limapoccoe</p>
                    </td>
                    <td>
                        <p>3 260</p>
                    </td>
                    <td>
                        <p>3 260</p>
                    </td>
                    <td>
                        <p>-</p>
                    </td>
                    <td>
                        <p>-</p>
                    </td>
                    <td>
                        <p>-</p>
                    </td>
                    <td>
                        <p>-</p>
                    </td>
                </tr>
                <tr>
                    <td>
                        <p>2</p>
                    </td>
                    <td>
                        <p>Laiya</p>
                    </td>
                    <td>
                        <p>2 907</p>
                    </td>
                    <td>
                        <p>2 907</p>
                    </td>
                    <td>
                        <p>-</p>
                    </td>
                    <td>
                        <p>-</p>
                    </td>
                    <td>
                        <p>-</p>
                    </td>
                    <td>
                        <p>-</p>
                    </td>
                </tr>
                <tr>
                    <td>
                        <p>3</p>
                    </td>
                    <td>
                        <p>Labuaja</p>
                    </td>
                    <td>
                        <p>2 251</p>
                    </td>
                    <td>
                        <p>2 111</p>
                    </td>
                    <td>
                        <p>1</p>
                    </td>
                    <td>
                        <p>139</p>
                    </td>
                    <td>
                        <p>-</p>
                    </td>
                    <td>
                        <p>-</p>
                    </td>
                </tr>
                <tr>
                    <td>
                        <p>4</p>
                    </td>
                    <td>
                        <p>Lebbotengae</p>
                    </td>
                    <td>
                        <p>1 135</p>
                    </td>
                    <td>
                        <p>1 135</p>
                    </td>
                    <td>
                        <p>-</p>
                    </td>
                    <td>
                        <p>-</p>
                    </td>
                    <td>
                        <p>-</p>
                    </td>
                    <td>
                        <p>-</p>
                    </td>
                </tr>
                <tr>
                    <td>
                        <p>5</p>
                    </td>
                    <td>
                        <p>Rompegading</p>
                    </td>
                    <td>
                        <p>1 716</p>
                    </td>
                    <td>
                        <p>1 716</p>
                    </td>
                    <td>
                        <p>-</p>
                    </td>
                    <td>
                        <p>-</p>
                    </td>
                    <td>
                        <p>-</p>
                    </td>
                    <td>
                        <p>-</p>
                    </td>
                </tr>
                <tr>
                    <td>
                        <p>6</p>
                    </td>
                    <td>
                        <p>Baji Pamai</p>
                    </td>
                    <td>
                        <p>1 421</p>
                    </td>
                    <td>
                        <p>1 421</p>
                    </td>
                    <td>
                        <p>-</p>
                    </td>
                    <td>
                        <p>-</p>
                    </td>
                    <td>
                        <p>-</p>
                    </td>
                    <td>
                        <p>-</p>
                    </td>
                </tr>
                <tr>
                    <td>
                        <p>7</p>
                    </td>
                    <td>
                        <p>Cenrana Baru</p>
                    </td>
                    <td>
                        <p>1 806</p>
                    </td>
                    <td>
                        <p>1 806</p>
                    </td>
                    <td>
                        <p>-</p>
                    </td>
                    <td>
                        <p>-</p>
                    </td>
                    <td>
                        <p>-</p>
                    </td>
                    <td>
                        <p>-</p>
                    </td>
                </tr>
                <tr>
                    <td colspan="2">
                        <p><strong>Jumlah</strong></p>
                    </td>
                    <td>
                        <p><strong>14 856</strong></p>
                    </td>
                    <td>
                        <p><strong>14 716</strong></p>
                    </td>
                    <td>
                        <p><strong>-</strong></p>
                    </td>
                    <td>
                        <p><strong>139</strong></p>
                    </td>
                    <td>
                        <p><strong>-</strong></p>
                    </td>
                    <td>
                        <p>-</p>
                    </td>
                </tr>
            </tbody>
        </table>
    </div>
    <hr>
    <h5>DATA SARANA DAN KEGIATAN IBADAH</h5>
    <div class="table-responsive">
        <table class="table table-success text-center table-hover">
            <tbody>
                <tr>
                    <th rowspan="2">

                        <p>NO</p>
                    </th>
                    <th rowspan="2">
                        <p>KELURAHAN/DESA</p>
                    </th>
                    <th colspan="6">
                        <p>BANYAKNYA SARANA/ TEMPAT IBADAH</p>
                    </th>
                </tr>
                <tr>
                    <th>
                        <p>Masjid</p>
                    </th>
                    <th>
                        <p>Mushallah</p>
                    </th>
                    <th>
                        <p>Gereja</p>
                    </th>
                    <th>
                        <p>Kuil</p>
                    </th>
                    <th>
                        <p>Wihara</p>
                    </th>
                    <th>
                        <p>Klenteng</p>
                    </th>
                </tr>
                <tr>
                    <td>
                        <p>1</p>
                    </td>
                    <td>
                        <p>Limapoccoe</p>
                    </td>
                    <td>
                        <p>11</p>
                    </td>
                    <td>
                        <p>-</p>
                    </td>
                    <td>
                        <p>-</p>
                    </td>
                    <td>
                        <p>-</p>
                    </td>
                    <td>
                        <p>-</p>
                    </td>
                    <td>
                        <p>-</p>
                    </td>
                </tr>
                <tr>
                    <td>
                        <p>2</p>
                    </td>
                    <td>
                        <p>Laiya</p>
                    </td>
                    <td>
                        <p>12</p>
                    </td>
                    <td>
                        <p>-</p>
                    </td>
                    <td>
                        <p>-</p>
                    </td>
                    <td>
                        <p>-</p>
                    </td>
                    <td>
                        <p>-</p>
                    </td>
                    <td>
                        <p>-</p>
                    </td>
                </tr>
                <tr>
                    <td>
                        <p>3</p>
                    </td>
                    <td>
                        <p>Labuaja</p>
                    </td>
                    <td>
                        <p>5</p>
                    </td>
                    <td>
                        <p>2</p>
                    </td>
                    <td>
                        <p>1</p>
                    </td>
                    <td>
                        <p>-</p>
                    </td>
                    <td>
                        <p>-</p>
                    </td>
                    <td>
                        <p>-</p>
                    </td>
                </tr>
                <tr>
                    <td>
                        <p>4</p>
                    </td>
                    <td>
                        <p>Lebbotengae</p>
                    </td>
                    <td>
                        <p>3</p>
                    </td>
                    <td>
                        <p>-</p>
                    </td>
                    <td>
                        <p>-</p>
                    </td>
                    <td>
                        <p>-</p>
                    </td>
                    <td>
                        <p>-</p>
                    </td>
                    <td>
                        <p>-</p>
                    </td>
                </tr>
                <tr>
                    <td>
                        <p>5</p>
                    </td>
                    <td>
                        <p>Rompegading</p>
                    </td>
                    <td>
                        <p>5</p>
                    </td>
                    <td>
                        <p>-</p>
                    </td>
                    <td>
                        <p>-</p>
                    </td>
                    <td>
                        <p>-</p>
                    </td>
                    <td>
                        <p>-</p>
                    </td>
                    <td>
                        <p>-</p>
                    </td>
                </tr>
                <tr>
                    <td>
                        <p>6</p>
                    </td>
                    <td>
                        <p>Baji Pamai</p>
                    </td>
                    <td>
                        <p>5</p>
                    </td>
                    <td>
                        <p>1</p>
                    </td>
                    <td>
                        <p>-</p>
                    </td>
                    <td>
                        <p>-</p>
                    </td>
                    <td>
                        <p>-</p>
                    </td>
                    <td>
                        <p>-</p>
                    </td>
                </tr>
                <tr>
                    <td>
                        <p>7</p>
                    </td>
                    <td>
                        <p>Cenrana Baru</p>
                    </td>
                    <td>
                        <p>5</p>
                    </td>
                    <td>
                        <p>-</p>
                    </td>
                    <td>
                        <p>-</p>
                    </td>
                    <td>
                        <p>-</p>
                    </td>
                    <td>
                        <p>-</p>
                    </td>
                    <td>
                        <p>-</p>
                    </td>
                </tr>
                <tr>
                    <td colspan="2">
                        <p><strong>Jumlah</strong></p>
                    </td>
                    <td>
                        <p><strong>47</strong></p>
                    </td>
                    <td>
                        <p><strong>3</strong></p>
                    </td>
                    <td>
                        <p><strong>1</strong></p>
                    </td>
                    <td>
                        <p>-</p>
                    </td>
                    <td>
                        <p>-</p>
                    </td>
                    <td>
                        <p>-</p>
                    </td>
                </tr>
            </tbody>
        </table>
    </div>
    <hr>
    <h5>DATA TANAH WAKAF</h5>
    <div class="table-responsive">
        <table class="table table-success text-center table-hover">
            <tbody>
                <tr>
                    <th rowspan="2">

                        <p>NO</p>
                    </th>
                    <th rowspan="2">
                        <p>KELURAHAN</p>
                        <p>/DESA</p>
                    </th>
                    <th colspan="2">
                        <p>Jumlah</p>
                    </th>
                    <th colspan="2">
                        <p>Masjid</p>
                    </th>
                    <th colspan="2">
                        <p>Langgar/Mushallah</p>
                    </th>
                    <th colspan="2">
                        <p>Madrasah/Sekolah</p>
                    </th>
                    <th colspan="2">
                        <p>Kuburan /Makam</p>
                    </th>
                    <th colspan="2">
                        <p>Sosial/Lain</p>
                    </th>
                </tr>
                <tr>
                    <th>
                        <p><strong>Lokasi </strong></p>
                    </th>
                    <th>
                        <p><strong>Luas M2</strong></p>
                    </th>
                    <th>
                        <p><strong>Lokasi </strong></p>
                    </th>
                    <th>
                        <p><strong>Luas M2</strong></p>
                    </th>
                    <th>
                        <p><strong>Lokasi </strong></p>
                    </th>
                    <th>
                        <p><strong>Luas M2</strong></p>
                    </th>
                    <th>
                        <p><strong>Lokasi </strong></p>
                    </th>
                    <th>
                        <p><strong>Luas M2</strong></p>
                    </th>
                    <th>
                        <p><strong>Lokasi </strong></p>
                    </th>
                    <th>
                        <p><strong>Luas M2</strong></p>
                    </th>
                    <th>
                        <p><strong>Lokasi </strong></p>
                    </th>
                    <th>
                        <p><strong>Luas M2</strong></p>
                    </th>
                </tr>
                <tr>
                    <td>
                        <p><strong>1</strong></p>
                    </td>
                    <td>
                        <p><strong>2</strong></p>
                    </td>
                    <td>
                        <p><strong>3</strong></p>
                    </td>
                    <td>
                        <p><strong>&nbsp;</strong></p>
                    </td>
                    <td>
                        <p><strong>5</strong></p>
                    </td>
                    <td>
                        <p><strong>6</strong></p>
                    </td>
                    <td>
                        <p><strong>7</strong></p>
                    </td>
                    <td>
                        <p><strong>8</strong></p>
                    </td>
                    <td>
                        <p><strong>9</strong></p>
                    </td>
                    <td>
                        <p><strong>10</strong></p>
                    </td>
                    <td>
                        <p><strong>11</strong></p>
                    </td>
                    <td>
                        <p><strong>12</strong></p>
                    </td>
                    <td>
                        <p><strong>13</strong></p>
                    </td>
                    <td>
                        <p><strong>14</strong></p>
                    </td>
                </tr>
                <tr>
                    <td>
                        <p>1</p>
                    </td>
                    <td>
                        <p>Limapoccoe</p>
                    </td>
                    <td>
                        <p>6</p>
                    </td>
                    <td>
                        <p>14016</p>
                    </td>
                    <td>
                        <p>6</p>
                    </td>
                    <td>
                        <p>14016</p>
                    </td>
                    <td>
                        <p>-</p>
                    </td>
                    <td>
                        <p>-</p>
                    </td>
                    <td>
                        <p>2</p>
                    </td>
                    <td>
                        <p>6,8</p>
                    </td>
                    <td>
                        <p>-</p>
                    </td>
                    <td>
                        <p>-</p>
                    </td>
                    <td>
                        <p>-</p>
                    </td>
                    <td>
                        <p>-</p>
                    </td>
                </tr>
                <tr>
                    <td>
                        <p>2</p>
                    </td>
                    <td>
                        <p>Laiya</p>
                    </td>
                    <td>
                        <p>9</p>
                    </td>
                    <td>
                        <p>4542</p>
                    </td>
                    <td>
                        <p>9</p>
                    </td>
                    <td>
                        <p>4542</p>
                    </td>
                    <td>
                        <p>-</p>
                    </td>
                    <td>
                        <p>-</p>
                    </td>
                    <td>
                        <p>-</p>
                    </td>
                    <td>
                        <p>-</p>
                    </td>
                    <td>
                        <p>-</p>
                    </td>
                    <td>
                        <p>-</p>
                    </td>
                    <td>
                        <p>-</p>
                    </td>
                    <td>
                        <p>-</p>
                    </td>
                </tr>
                <tr>
                    <td>
                        <p>3</p>
                    </td>
                    <td>
                        <p>Labuaja</p>
                    </td>
                    <td>
                        <p>5</p>
                    </td>
                    <td>
                        <p>9 838</p>
                    </td>
                    <td>
                        <p>3</p>
                    </td>
                    <td>
                        <p>977</p>
                    </td>
                    <td>
                        <p>1</p>
                    </td>
                    <td>
                        <p>-</p>
                    </td>
                    <td>
                        <p>-</p>
                    </td>
                    <td>
                        <p>-</p>
                    </td>
                    <td>
                        <p>-</p>
                    </td>
                    <td>
                        <p>-</p>
                    </td>
                    <td>
                        <p>-</p>
                    </td>
                    <td>
                        <p>-</p>
                    </td>
                </tr>
                <tr>
                    <td>
                        <p>4</p>
                    </td>
                    <td>
                        <p>Lebbotengae</p>
                    </td>
                    <td>
                        <p>5</p>
                    </td>
                    <td>
                        <p>2285</p>
                    </td>
                    <td>
                        <p>5</p>
                    </td>
                    <td>
                        <p>2285</p>
                    </td>
                    <td>
                        <p>-</p>
                    </td>
                    <td>
                        <p>-</p>
                    </td>
                    <td>
                        <p>-</p>
                    </td>
                    <td>
                        <p>-</p>
                    </td>
                    <td>
                        <p>-</p>
                    </td>
                    <td>
                        <p>-</p>
                    </td>
                    <td>
                        <p>-</p>
                    </td>
                    <td>
                        <p>-</p>
                    </td>
                </tr>
                <tr>
                    <td>
                        <p>5</p>
                    </td>
                    <td>
                        <p>Rompegading</p>
                    </td>
                    <td>
                        <p>5</p>
                    </td>
                    <td>
                        <p>3210</p>
                    </td>
                    <td>
                        <p>5</p>
                    </td>
                    <td>
                        <p>3210</p>
                    </td>
                    <td>
                        <p>-</p>
                    </td>
                    <td>
                        <p>-</p>
                    </td>
                    <td>
                        <p>-</p>
                    </td>
                    <td>
                        <p>-</p>
                    </td>
                    <td>
                        <p>-</p>
                    </td>
                    <td>
                        <p>-</p>
                    </td>
                    <td>
                        <p>-</p>
                    </td>
                    <td>
                        <p>-</p>
                    </td>
                </tr>
                <tr>
                    <td>
                        <p>6</p>
                    </td>
                    <td>
                        <p>Baji Pamai</p>
                    </td>
                    <td>
                        <p>7</p>
                    </td>
                    <td>
                        <p>3312</p>
                    </td>
                    <td>
                        <p>7</p>
                    </td>
                    <td>
                        <p>3312</p>
                    </td>
                    <td>
                        <p>-</p>
                    </td>
                    <td>
                        <p>-</p>
                    </td>
                    <td>
                        <p>-</p>
                    </td>
                    <td>
                        <p>-</p>
                    </td>
                    <td>
                        <p>-</p>
                    </td>
                    <td>
                        <p>-</p>
                    </td>
                    <td>
                        <p>-</p>
                    </td>
                    <td>
                        <p>-</p>
                    </td>
                </tr>
                <tr>
                    <td>
                        <p>7</p>
                    </td>
                    <td>
                        <p>Cenrana Baru</p>
                    </td>
                    <td>
                        <p>7</p>
                    </td>
                    <td>
                        <p>6860</p>
                    </td>
                    <td>
                        <p>7</p>
                    </td>
                    <td>
                        <p>6860</p>
                    </td>
                    <td>
                        <p>-</p>
                    </td>
                    <td>
                        <p>-</p>
                    </td>
                    <td>
                        <p>-</p>
                    </td>
                    <td>
                        <p>-</p>
                    </td>
                    <td>
                        <p>-</p>
                    </td>
                    <td>
                        <p>-</p>
                    </td>
                    <td>
                        <p>-</p>
                    </td>
                    <td>
                        <p>-</p>
                    </td>
                </tr>
                <tr>
                    <td colspan="2">
                        <p><strong>Jumlah</strong></p>
                    </td>
                    <td>
                        <p><strong>44</strong></p>
                    </td>
                    <td>
                        <p><strong>44063</strong></p>
                    </td>
                    <td>
                        <p><strong>42</strong></p>
                    </td>
                    <td>
                        <p><strong>35202</strong></p>
                    </td>
                    <td>
                        <p><strong>-</strong></p>
                    </td>
                    <td>
                        <p><strong>-</strong></p>
                    </td>
                    <td>
                        <p>2</p>
                    </td>
                    <td>
                        <p>6,8</p>
                    </td>
                    <td>
                        <p>-</p>
                    </td>
                    <td>
                        <p>-</p>
                    </td>
                    <td>
                        <p>-</p>
                    </td>
                    <td>
                        <p>-</p>
                    </td>
                </tr>
            </tbody>
        </table>
    </div>

</div>