<div class="container">
    <div class="my-5">
        <h3>Info Pendaftaran Haji</h3>
        <hr>
        <h3 style='margin-right:0cm;margin-left:0cm;font-weight:bold;margin:0cm;margin-bottom:.0001pt;vertical-align:baseline;'><span style='font-size: 27px; color: rgb(53, 53, 53);'>Tata Cara Pendaftaran Haji</span></h3>
        <h1 style='margin-right:0cm;margin-left:0cm;font-size:32px;font-weight:bold;margin:0cm;margin-bottom:.0001pt;text-align:center;vertical-align:baseline;'><span style="font-family: 'Times New Roman', Times, serif;"><span style="font-size:16px;color:#353535;">&nbsp;</span></span></h1>
        <p style='margin-right:0cm;margin-left:0cm;font-size:15px;font-family:"Calibri","sans-serif";margin-top:0cm;margin-bottom:21.0pt;line-height:115%;vertical-align:baseline;'><span style="font-family: 'Times New Roman', Times, serif;"><strong><span style="color:black;">A. PERSYARATAN PENDAFTARAN HAJI</span></strong></span></p>
        <p style='margin-right:0cm;margin-left:0cm;font-size:15px;font-family:"Calibri","sans-serif";margin-top:0cm;margin-bottom:21.0pt;line-height:150%;vertical-align:baseline;'><span style="font-family: 'Times New Roman', Times, serif;"><span style="color:black;">1. Beragama Islam;<br> 2. Berusia Minimal 12 Tahun pada saat pendaftaran;<br> 3. Bagi yang sudah haji, bisa mendaftar kembali setelah 10 (sepuluh) tahun keberangkatan haji terakhir;<br> 4. Fotocopy KTP yang masih berlaku sesuai dengan domisili 3 lembar;<br> 5. Fotocopy Kartu Keluarga 1 lembar; ( menunjukkan yang asli)<br> 6. Fotocopy Akte Kelahiran / kutipan akta nikah;<br> 7. Pas Foto terbaru berwarna 3 x 4 = 12 lembar dan 4 x 6 = 2 lembar, dengan latar belakang /background putih dengan ketentuan:<br> a. Tampak wajah 80% (persen);<br> b. Warna baju/kerudung harus kontras dengan latar belakang;<br> c. Tidak memakai pakaian dinas;<br> d. Tidak memakai kacamata;<br> e. Bagi calon jemaah haji wanita wajib menggunakan busan muslimah;<br>8. Gubernur dapat menambahkan persyaratan berupa surat keterangan domisili.</span></span></p>
        <h2 style="margin: 2pt 0cm 0.0001pt; line-height: 2; font-size: 17px; font-family: Cambria, serif; color: rgb(54, 95, 145); font-weight: normal;"><span style="font-family: 'Times New Roman', Times, serif;"><strong><span style="font-size: 15px; line-height: 200%; color: windowtext;">B. PROSEDUR PENDAFTARAN HAJI</span></strong></span></h2>
        <p style='margin-right:0cm;margin-left:0cm;font-size:15px;font-family:"Calibri","sans-serif";margin-top:0cm;margin-bottom:.0001pt;line-height:150%;margin:0cm;vertical-align:baseline;'><span style="font-family: 'Times New Roman', Times, serif;"><span style="line-height:150%;color:black;">1. <strong><span style="border:none windowtext 1.0pt;padding:0cm;">BANK</span></strong><span style="border:none windowtext 1.0pt;padding:0cm;">&nbsp;<strong>PENERIMA&nbsp;</strong><strong>SETORAN BPIH ( BPS &ndash; BPIH)</strong></span></span></span></p>
        <p style="font-size: 15px; font-family: Calibri, sans-serif; line-height: 1.5; margin: 0cm; vertical-align: baseline;"><span style="font-family: 'Times New Roman', Times, serif;"><span style="color:black;">Datang ke Bank Penerima Setoran (BPS) Syari&rsquo;ah untuk membuka rekening tabungan haji dengan setoran minimal Rp. 25.000.000,- ( dua puluh lima juta rupiah )<br> a. Membawa data/identitas pribadi berupa KTP, Kartu keluarga ( C1 ), Akte Nikah/Akte Lahir dan membuka rekening tabungan haji;<br> b. Meminta untuk diterbitkan <strong><span style="border:none windowtext 1.0pt;padding:0cm;">NOMOR VALIDASI</span></strong> oleh Bank;<br> c. Masa berlaku <strong><span style="border:none windowtext 1.0pt;padding:0cm;">NOMOR VALIDASI</span></strong> 5 hari kerja terhitung setelah menerima dari BANK;<br>d. Membawa pasfoto berwarna 3 x 4 = 5 lembar dan 4 x 6 = 1 lembar dengan background/latar belakang putih , tampak 80 % wajah.</span></span></p>
        <p style="margin: 0cm 0cm 21pt; font-size: 15px; font-family: Calibri, sans-serif; line-height: 1.5; vertical-align: baseline;"><span style="font-family: 'Times New Roman', Times, serif;"><span style="color:black;">Bank Penerima setoran menerbitkan bukti setoran awal BPIH ( Biaya Pendaftaran Ibadah Haji ) sebanyak 5 lembar dengan rincian :<br> a. Lembar pertama bermaterai Rp. 6000,- untuk calon jemaah haji;<br> b. Lembar kedua untuk BPS BPIH ( Bank Penerima Setoran biaya Pendaftaran ibadah haji );<br> c. Lembar ketiga untuk Kantor Kementerian Agama Kab Maros<br> d. Lembar keempat untuk Kanwil Kemenag. Maros;<br>e. Lembar kelima untuk Dirjen. PHU Kemenag RI.</span></span></p>
        <p style='margin-right:0cm;margin-left:0cm;font-size:15px;font-family:"Calibri","sans-serif";margin-top:0cm;margin-bottom:.0001pt;line-height:150%;margin:0cm;vertical-align:baseline;'><span style="font-family: 'Times New Roman', Times, serif;"><span style="line-height:150%;color:black;">2.<strong><span style="border:none windowtext 1.0pt;padding:0cm;">&nbsp;KANTOR KEMENTERIAN AGAMA KAB MAROS</span></strong></span></span></p>
        <p style="margin: 0cm 0cm 21pt; font-size: 15px; font-family: Calibri, sans-serif; line-height: 1.5; vertical-align: baseline;"><span style="font-family: 'Times New Roman', Times, serif;"><span style="color:black;">a. Calon jemaah yang bersangkutan datang langsung ke Kantor Kemenag. Maros ( Seksi penyelengaraan Haji dan Umroh );<br> b. Diterima oleh petugas bagian pendaftaran untuk verifikasi kelengkapan berkas pendaftarannya meliputi :<br> 1) Membawa setoran awal BPIH ( Biaya Penyelenggaraan Ibadah Haji ) dari Bank Penerima setoran;<br> 2) Lembar 1 setoran awla BPIH ( warna putih ) diterima kembali oleh jemaah, lembar 3, 4 dan 5 BPIH disimpan di Kementerian Agama Kab Maros<br> 3) Fotocopy KTP 3 lembar;<br> 4) Fotocopy bukti rekening setoran tabungan Haji Rp.25.000.000;<br> 5) Fotocopy akte nikah / akte lahir = 1 lembar<br> 6) Fotocopy Kartu Keluarga ( C1 );<br>&nbsp;7) Pasfoto berwarna 3 x 4 = 6 lembar dan 4 x 6 = 1 lembar tampak wajah 80 %.</span></span></p>
        <p style='margin-right:0cm;margin-left:0cm;font-size:15px;font-family:"Calibri","sans-serif";margin-top:0cm;margin-bottom:.0001pt;line-height:150%;margin:0cm;vertical-align:baseline;'><span style="font-family: 'Times New Roman', Times, serif;"><span style="line-height:150%;color:black;">3. <strong><span style="border:none windowtext 1.0pt;padding:0cm;">SISKOHAT ( SISTEM INFORMASI dan KOMPUTERISASI HAJI TERPADU )</span></strong></span></span></p>
        <p style="font-size: 15px; font-family: Calibri, sans-serif; line-height: 1.5; margin: 0cm; vertical-align: baseline;"><span style="font-family: 'Times New Roman', Times, serif;"><span style="color:black;">a. Jemaah yang bersangkutan masuk ke ruangan SISKOHAT ( Sistem Informasi dan Komputerisasi Haji Terpadu ) untuk melakukan proses wawancara, entry <strong><span style="border:none windowtext 1.0pt;padding:0cm;">NOMOR VALIDASI</span></strong> dari bank, pengambilan foto dan rekam sidik jari untuk mendapatkan <strong><span style="border:none windowtext 1.0pt;padding:0cm;">NOMOR PORSI HAJI</span></strong>;<br>&nbsp;b. Cetak berkas SPPH ( Surat pendaftaran Pergi Haji ) sejumlah 5 lembar.</span></span></p>
        <br>
        <p style='font-size:15px;font-family:"Calibri","sans-serif";margin-top:1cm;margin-bottom:.0001pt;line-height:115%;margin:0cm;vertical-align:baseline;'><span style="font-family: 'Times New Roman', Times, serif;"><span style="color:black;">4. <strong><span style="border:none windowtext 1.0pt;padding:0cm;">PROSES PENDAFTARAN HAJI SELESAI</span></strong></span></span></p>
        <p style="font-size: 15px; font-family: Calibri, sans-serif; line-height: 1.5; margin: 0cm; vertical-align: baseline;"><span style="font-family: 'Times New Roman', Times, serif;"><span style="color:black;">a. Calon jemaah medapatkan lembar kesatu berkas SPPH ( Surat Pendaftaran Pergi haji ) yang didalam tertera <strong><span style="border:none windowtext 1.0pt;padding:0cm;">NOMOR PORSI</span></strong> yang telah ditandatangani dan dibubuhi stempel dinas oleh petugas Kantor Kementeriana Agama Kab Maros dan masing &ndash; masing diberi pasfoto 3 x 4 ;<br> b. Lembar kedua kelima di simpan di Kantor Kementerian Agama Kab Maros <br>&nbsp;c. Menunggu pemangilan pelunasan BIPH sesuai dengan waitinglistnya , adapun besaranya pelunasan menunggu dikeluarkannya Peraturan Preside tentang Pelunasan BPIH sesuai dengan nomor porsi calon jemaah haji yang diberangkatkan pada tahun tersebut.</span></span></p>
        <h3 style="margin: 1cm 0cm 0.0001pt; line-height: 2; font-size: 15px; font-family: Cambria, serif; color: rgb(79, 129, 189); font-weight: bold; vertical-align: baseline;"><span style="font-family: 'Times New Roman', Times, serif;"><span style="font-size: 16px; line-height: 150%; color: rgb(58, 58, 58);">C. TATA CARA PELUNASAN HAJI</span></span></h3>
        <p style="margin: 0cm 0cm 21pt; font-size: 15px; font-family: Calibri, sans-serif; line-height: 1.5; vertical-align: baseline;"><span style="font-family: 'Times New Roman', Times, serif;"><span style="color:black;">Pastikan nama calon jemaah telah tertera dalam daftar calon jemaah yang berhak melunasi BPIH tahap I maupun tahap II pada tahin keberangkatan haji;<br>Besaran Pelunasan Haji menunggu Peraturan Presiden yang mengatur besaran BPIH tahun keberangkatan calomn jemaah haji;</span></span></p>
        <h2 style="margin: 2pt 0cm 0.0001pt; line-height: 2; font-size: 17px; font-family: Cambria, serif; color: rgb(54, 95, 145); font-weight: normal;"><span style="font-family: 'Times New Roman', Times, serif;"><strong><span style="color: windowtext;">PERSYARATAN</span></strong></span></h2>
        <p style="margin: 0cm 0cm 21pt; font-size: 15px; font-family: Calibri, sans-serif; line-height: 1.5; vertical-align: baseline;"><span style="font-family: 'Times New Roman', Times, serif;"><span style="color:black;">1. Fotocopy KTP 3 lembar;<br> 2. Pas Foto terbaru berwarna 3 x 4 = 12 lembar dan 4 x 6 = 2 lembar , dengan latar belakang /background putih tampak wajah 80 %<br> 3. Bukti Setoran Awal BPIH yang disimpan jemaah;<br> 4. Membawa buku tabungan haji<br> 5. SPPH ( Surat Pendaftaran Pergi Haji ) lembar kesatu yang disimpan jemaah yang menunjukkan NOMOR PORSI;<br>&nbsp;6. Membayar kekurangan BPIH untuk menerima bukti setor pelunasan BPIH ( Biaya Penyelenggaraan Ibadah Haji ) dari Bank Penerimaa Setoran.</span></span></p>
        <h2 style="margin: 2pt 0cm 0.0001pt; line-height: 2; font-size: 17px; font-family: Cambria, serif; color: rgb(54, 95, 145); font-weight: normal;"><span style="font-family: 'Times New Roman', Times, serif;"><strong><span style="color: windowtext;">PROSEDUR PELUNASAN HAJI</span></strong></span></h2>
        <p style="margin: 0cm 0cm 21pt; font-size: 15px; font-family: Calibri, sans-serif; line-height: 1.5; vertical-align: baseline;"><span style='color: black;'>1. Calon jemaah datang ke bank ( BPS BPIH ) untuk melunasi kekurangan biaya Setoran Lunas BPIH;<br> 2. Menerima Bukti Setoran lunas dari bank penerima setoran;<br> 3. Menyerahkan Bukti Setoran Lunas BPIH dari bank ke Kantor Kementerian Agama Kab Maros ( Seksi PHU ) untuk proses administrator dan info mengenai kewajiban calon jemaah pasca pelunasan BPIH seperti tes kesehatan dll.</span></p>
    </div>
</div>